// Short teaching definitions; edit or add entries here.
const CONVENTION_GLOSSARY = {
  "AI": "Artificial intelligence: machines performing tasks associated with human intelligence.",
  "HUD": "Heads-up display: on-screen game information such as health or score.",
  "POV-shots": "Shots showing what a character sees.",
  "all-ages-appeal": "Elements intended to engage both younger and older audiences.",
  "archive": "Previously recorded footage, images or sound reused in a text.",
  "artefact": "An object with special historical or magical significance.",
  "awkward-pause": "A silence used to create discomfort or comedy.",
  "banter": "Playful, teasing conversation between characters.",
  "boss-fights": "Battles against especially powerful game opponents.",
  "chase": "A sequence in which someone pursues someone else.",
  "close-calls": "Moments when a character narrowly avoids danger.",
  "combos": "Linked game actions that produce a stronger attack or effect.",
  "countdown": "A visible or stated limit on the time remaining.",
  "crew-roles": "Specialist jobs within a team, such as driver or hacker.",
  "cut-to-beat": "Editing shots to match the rhythm of the music.",
  "cybernetic-body": "A body enhanced or altered with machine components.",
  "declaration": "An explicit statement of love or commitment.",
  "double-cross": "Betraying someone who believed you were their ally.",
  "dragon": "A mythical creature, often associated with power or danger.",
  "dread": "Sustained anticipation that something terrible will happen.",
  "dream-logic": "Events following dreamlike associations rather than everyday logic.",
  "duel": "A formal confrontation between two opponents.",
  "dusty-outpost-planet": "A remote, rugged settlement on another world.",
  "exaggeration": "Making actions or features larger than life.",
  "explosive-climax": "A final high-intensity sequence of destruction or action.",
  "femme-fatale": "A seductive, dangerous woman archetype often found in noir.",
  "fights": "Physical conflict between characters.",
  "final-girl": "A surviving female character who confronts the killer in a slasher.",
  "fly-on-the-wall": "A style that appears to watch events without intervening.",
  "frontier": "A borderland framed as the edge of settlement or authority.",
  "frontier-in-space": "Outer space presented as a new frontier.",
  "futurism": "Imagining future technologies, societies and environments.",
  "gaslight": "Manipulating someone into doubting their own perceptions.",
  "hacking": "Accessing or manipulating computer systems.",
  "hand-to-hand": "Close-range physical combat.",
  "handheld": "Camera movement produced by holding the camera rather than fixing it.",
  "happy-ever-after": "An ending suggesting lasting happiness for the couple.",
  "interrogation": "Intensive questioning to obtain information.",
  "interview-gags": "Comedy created through interview-style scenes.",
  "investigation": "Gathering evidence to uncover what happened.",
  "isolation": "Separating characters from help or safety.",
  "jeopardy": "A situation involving danger or serious risk.",
  "jump-scare": "A sudden image or sound intended to startle the audience.",
  "lawman-vs-outlaw": "Conflict between an enforcer of law and someone outside it.",
  "level-progression": "Advancing through stages or increasing levels in a game.",
  "lip-sync": "Matching mouth movements to a recorded voice or song.",
  "low-key-lighting": "Lighting with strong contrasts and substantial shadow.",
  "masked-killer": "A killer whose face or identity is concealed by a mask.",
  "meet-cute": "An amusing or memorable first meeting between romantic leads.",
  "megacorp": "An extremely powerful corporation, often dominating society.",
  "mentor": "A guide who teaches or supports the protagonist.",
  "miscommunication": "Misunderstandings caused by failed or incomplete communication.",
  "montage": "A sequence of edited shots that compresses time or builds meaning.",
  "moral-ambiguity": "Uncertainty about whether actions or characters are right or wrong.",
  "nemesis": "A persistent rival or major enemy.",
  "neon-noir": "Noir mood and imagery combined with neon-lit urban settings.",
  "observational": "Documentary style emphasising watching events as they unfold.",
  "obstacles": "Barriers preventing characters from reaching their goals.",
  "one-liners": "Short, memorable remarks, often humorous.",
  "origin-story": "An account of how a character acquired their identity or powers.",
  "party-gone-wrong": "A celebration that turns into danger or disaster.",
  "performance": "Showing an artist singing, playing or performing for an audience.",
  "plan-montage": "Edited shots presenting preparations for a scheme or heist.",
  "police-procedural": "A focus on the methods and routines of police work.",
  "posse": "A group assembled to pursue or capture someone.",
  "post-credits": "A scene appearing during or after the closing credits.",
  "prophecy": "A prediction that shapes expectations about future events.",
  "pursuit": "An extended effort to follow, catch or track someone.",
  "quest": "A journey undertaken to achieve a significant goal.",
  "reality-blur": "Uncertainty about what is real, imagined or perceived.",
  "reconciliation": "Restoring a relationship after conflict or separation.",
  "red-herring": "A misleading clue that diverts attention from the truth.",
  "reveals": "Moments when previously hidden information becomes known.",
  "set-pieces": "Elaborately staged sequences designed for dramatic impact.",
  "sheriff": "A local law officer commonly featured in Westerns.",
  "stakeout": "Watching a location or person while waiting for evidence.",
  "standoff": "A tense confrontation in which neither side backs down.",
  "stunts": "Planned physical feats used to create action or spectacle.",
  "stylisation": "Deliberate departures from naturalistic appearance or behaviour.",
  "suit-up": "A sequence showing a hero preparing and putting on their costume.",
  "talking-head": "An interview shot focused on a person speaking to camera or interviewer.",
  "team-up": "Characters joining forces to achieve a shared goal.",
  "tech-anxiety": "Fear or unease about technology and its consequences.",
  "thought-experiment": "An imagined situation used to explore an idea or its consequences.",
  "ticking-clock": "A deadline that creates urgency and suspense.",
  "transgression": "Crossing a social, moral or cultural boundary.",
  "twist": "An unexpected development that changes the audience’s understanding.",
  "unreliable-narrator": "A storyteller whose account cannot be fully trusted.",
  "vault-tech": "Security equipment or techniques involved in accessing a vault.",
  "visual-gag": "A joke communicated primarily through images or action.",
  "visual-motif": "A recurring visual element that builds meaning.",
  "voice-of-god": "Authoritative documentary narration from an unseen speaker.",
  "voice-over": "Speech heard over images without the speaker visibly delivering it.",
  "world-building": "Creating the setting, rules and culture of a fictional world."
};
